### ISSUE TITLE
Typescript error when trying to run

### ISSUE THREAD

**Issue by RKukharchuk** [FlatFilers/getting-started#51]
Node version:  v20.10.0

I'm getting this error, when trying to run project from master branch:

`TS2345: Argument of type '(client: FlatfileListener) => void' is not assignable to parameter of type '(handler: FlatfileListener) => void'.
  Types of parameters 'client' and 'handler' are incompatible.
    Type 'import("node_modules/@flatfile/listener/dist/index").FlatfileListener' is not assignable to type 'import("node_modules/@flatfile/plugin-record-hook/node_modules/@flatfile/listener/dist/flatfile.listener").FlatfileListener'.
      Types of property 'mount' are incompatible.
        Type '(driver: import("node_modules/@flatfile/listener/dist/index").EventDriver) => import("node_modules/@flatfile/listener/dist/index").FlatfileListener' is not assignable to type '(driver: import("node_modules/@flatfile/plugin-record-hook/node_modules/@flatfile/listener/dist/event-drivers/_EventDriver").EventDriver) => import("node_modules/@flatfile/plugin-record...'.
          Types of parameters 'driver' and 'driver' are incompatible.
            Type 'import("node_modules/@flatfile/plugin-record-hook/node_modules/@flatfile/listener/dist/event-drivers/_EventDriver").EventDriver' is not assignable to type 'import("node_modules/@flatfile/listener/dist/index").EventDriver'.
              Types of property '_handler' are incompatible.
                Type 'import("node_modules/@flatfile/plugin-record-hook/node_modules/@flatfile/listener/dist/events/event.handler").EventHandler' is not assignable to type 'import("node_modules/@flatfile/listener/dist/index").EventHandler'.
                  Property 'listeners' is protected but type 'EventHandler' is not a class derived from 'EventHandler'.`

**Comment by Arsik36** [comment]
Hey, thank you for reaching out to us. If you're running the latest version of any of our plugins, you need to also have the latest version of the Listener. Otherwise you'll get the typescript error.<br><br>If you are not running any plugin, can you please share a screen recording with me? I'd love to see when you get this error, your package versions, and what is inside of your listener file

**Comment by Arsik36** [comment]
Perfect, that was going to be my next suggestion :) <br>As a developer here, I run `npm outdated` at least 1-2 times daily to make sure I work on the latest versions. In the future if you see anything not working properly, that is a good first thing to do
